### ISSUE TITLE
Use custom types

### ISSUE THREAD

**Issue by dmantula** [glebreutov/SaboteurGame#4]
https://github.com/glebreutov/SaboteurGame/blob/a9925d2d6acf894db1872e89d8820d55412d81d6/src/main/scala/gr/saboteur/DungeonGraph.scala#L77

The type `(Int, Int)` is not meaningful at all. Especially if you add more fields to this tuple in future. Thus, use the following construct:
```
type Position = (Int, Int)
```
.. and use it wherever you mean it's a position, not something else.

At source code level it will be still `(Int, Int)`, and you can convert `(Int, Int)` to `Position` whenever you want.

**Comment by glebreutov** [comment]
custom types are nice
