### ISSUE TITLE
Create the Set once

### ISSUE THREAD

**Issue by dmantula** [glebreutov/SaboteurGame#5]
https://github.com/glebreutov/SaboteurGame/blob/a9925d2d6acf894db1872e89d8820d55412d81d6/src/main/scala/gr/saboteur/DungeonGraph.scala#L63

1) Magic numbers detected – extract them as constants
2) Create the Set once in a separate place, and name it properly
3) `fooSet.contains(bar)` ~> `fooSet(bar)`

**Comment by glebreutov** [comment]
fixed
